name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # 매일 새벽 3시 KST / GitHub cron은 UTC 기준

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: yejingksdpwls

          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Seoul

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
